[package]
name = "moonrs"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.6.5"
nalgebra = "0.33.0"
statrs = "0.17.1"
pyo3 = "0.22.1"

[lib]
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "moonrs"
